# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: check-json
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: \.min\.js$
    -   id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.219'
    hooks:
    - id: ruff  # See 'setup.cfg' for args
      args: [nbsite]
      files: nbsite/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [css]
ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
