{% set sdata = load_setup_py_data() %}

package:
  name: nbsite
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    {% for group,epoints in sdata.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}  

requirements:
  host:
    - python
    - setuptools
  run:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}

    {% for dep in sdata['extras_require']['gallery'] %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    {% for dep in sdata['extras_require']['tests'] %}
    - {{ dep }}
    {% endfor %}
  imports:
    - nbsite

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
